# Generated by Django 4.0.4 on 2022-05-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_carsappuser_email_carsappuser_gender_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsappuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
