# Generated by Django 4.0.4 on 2022-05-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0002_usercar_odometer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercar',
            name='first_reg',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
